### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by qoqosz** [bellecp/fast-p#3] opened 2018-07-25 19:28 UTC
When I tried running the p command I got the error like this:
```
[qoqosz:~/Downloads]$ p   
Loading _of_Combinatorial_Topology.pdf...  
Loading son,_Ronald_L.pdf...  
Loading toip-depo.pdf...  .pdf             
p:48: no such file or directory: /Users/qoqosz/.cache/pdftotext/00ce81e5cab6f38ftebooks-tmp/Foundations_of_Combinatorial_Topology.pdf
```
I'm on a Mac and have installed all the requirements. Not sure what steps should I list to make this issue somehow reproducible. Is it possible that space in filenames could be a problem?

**Comment by bellecp** [comment] 2018-07-25 21:00
I recall having some trouble making it work on a mac. What is your ``$ bash --version``?
The bash provided by OSX is only v3. Could you try to run the script inside bash v4, installed with homebrew?

**Comment by maxgillett** [comment] 2018-07-25 21:18
Getting the same error with bash v4.4.23.

**Comment by bellecp** [comment] 2018-07-25 21:21
What is your OS and the output of the commands
- ``bash --version``
- ``awk --version``
- ``grep --version``
- ``ag --version``
- ``xargs --version``
- ``xxh64sum --version``
- ``pdftotext -v``

**Comment by bellecp** [comment] 2018-07-25 21:31
I guess that the pdf is ``ebooks-tmp/Foundations_of_Combinatorial_Topology.pdf`` and that its text has been extracted to ``/Users/qoqosz/.cache/pdftotext/00ce81e5cab6f38f``. Correct?

**Comment by bellecp** [comment] 2018-07-25 21:37
The problem is with the use of \t (tab character) to separate the fields in awk at https://github.com/bellecp/fast-p/blob/master/p#L48
Instead of providing $2 being the path-to-pdf ebooks-tmp/Foundations_of_Combinatorial_Topology.pdf and $2 being the hash 00ce81e5cab6f38f, the two fields are not separated and it wrongly concatenates the filename after the path to ~/.cache/pdftotext/00ce81e5cab6f38f. I am not sure why tab-separated fields would fail on OSx.

**Comment by bellecp** [comment] 2018-07-25 21:57
I would start by adding ``echo $LINE`` when entering the while loop at https://github.com/bellecp/fast-p/blob/master/p#L46 ; is a tab character correctly used to separate the two fields in the echoed line?

(It will be difficult for me to debug without having access to an OSX machine).

**Comment by qoqosz** [comment] 2018-07-26 16:32
Similar versions to what maxgillett listed with the following differences:

- bash: 3.2.57
- grep: grep (GNU grep) 3.1
- pdftotext version 3.03

I tried adding `echo $LINE` but I can't see a difference; the content of the pdf was not extracted to /Users/qoqosz/.cache/pdftotext/00ce81e5cab6f38f as the file is missing.

**Comment by bellecp** [comment] 2018-07-26 19:22
What's the output of gawk --version, awk --version and the top line of man awk?

**Comment by bellecp** [comment] 2018-07-26 19:39
If you checkout the branch gawk from the repository, do ``rm ~/.cache/pdftotext/*`` and try the command p again, what error do you get?

**Comment by qoqosz** [comment] 2018-07-26 20:06
I did but it's still the same.

**Comment by maxgillett** [comment] 2018-07-26 20:16
Same here. I should note that I get this error for around 1-2% of my PDFs, and when I look in `~/.cache/pdftototext/`, the ones that are "processed" are empty files, so no searching works.

**Comment by bellecp** [comment] 2018-07-26 21:16
What about the command
```
 ag -g ".pdf$" \
    | awk 'BEGIN {FS="\t"; OFS="\t"}; {command=" pdftotext -f 1 -l 1 \""$0"\" - 2>/dev/null | tr \"\n\" \"\n\" ";
        while( (command|getline foo) >0 ) {
            print $0, foo;
        } close(command); 
    }' \
     | fzf -e  -d '\t' \
     --preview-window up:60% \
     --preview 'echo {1} | grep -E "^|$v" -i --color=always;
             v=$(echo {q} | tr " " "|");
             pdftotext -f 1 -l 1 {1} - | grep -E "^|$v" -i --color=always' \
     | awk 'BEGIN {FS="\t"; OFS="\t"}; {print "\""$1"\""}' \
     | xargs open
```
? It's a shorter version that does not do caching.

**Comment by maxgillett** [comment] 2018-07-26 21:22
Yep, that works!

With that, I just also have `grep: empty (sub)expression` in the first line of the preview window (which I had previously), and when no match is found, the error: `I/O Error: Couldn't open file '': No such file or directory`. These are simpler issues to debug though

**Comment by bellecp** [comment] 2018-07-26 21:32
I believe ``grep: empty (sub)expression`` can be fixed by using GNU grep instead of your BSD grep.

It works but without cache. Without cache it will be very slow for 100+ pdf files, since pdftotext is run on-the-fly.

**Comment by bellecp** [comment] 2018-07-30 02:03
For speed and interoperability, I am consdering using a go binary instead of the bash scripts that generate many errors on OSX. @maxgillett , @qoqosz , could you let me know if https://github.com/bellecp/fast-p/blob/master/README-OSX.md works on OSX?

**Comment by qoqosz** [comment] 2018-07-30 05:30
@bellecp yes, it works. Thank you!

**Comment by maxgillett** [comment] 2018-07-30 17:00
Works for me too. Thanks!

**Closed as completed** 2018-07-31 04:17 UTC
